### ISSUE TITLE
PROVIDER_URL?

### ISSUE THREAD

**Issue by compojoom** [commonprefix/kevlar#6]
PROVIDER_URL from the .env.example doesn't seem to be used anywhere in the code? What is the intended purpose of that argument - specifying an RPC endpoint, instead of the hardcoded default RPCs?

**Comment by shresthagrawal** [comment]
Thanks for pointing that out. I will fix it to use PROVIDER_URL env to override the default

**Comment by rista404** [comment]
Please use `--rpc` cli argument. I've removed `PROVIDER_URL` from `.env.example` to avoid confusion.
